services:
  postgres:
    image: postgres:14-alpine
    container_name: dai_postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dai_network

  auth:
    build:
      dockerfile: Dockerfile
    container_name: dai_auth_service
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    networks:
      - dai_network

volumes:
  pgdata:

networks:
  dai_network:
    driver: bridge